### ISSUE TITLE
Question about Reversal Curse Experiment

### ISSUE THREAD

**Issue by richardzhuang0412** [ML-GSAI/SMDM#1]
Appreciate the great work! I have two questions:
1) Is the ability to solve reversal curse an emergent ability as you scale up the MDM?
2) I am trying to replicate your result for reversal curse but I was originally referring to https://github.com/louaaron/Score-Entropy-Discrete-Diffusion for implementation. Not sure if you have referred to their code exactly but are you using the same implementation?

**Comment by nieshenx** [comment]
Thank you for your interest in our work!

1. We haven't conducted a systematic study on this issue, but a smaller MDM can still effectively break the reversal curse. I provide the results of MDM with 220M parameters as follows. 
![reverse_220m](https://github.com/user-attachments/assets/e6bc788a-ae34-4991-b59b-a6214cb6a5ac)

2. Our implementation is entirely different from SEDD. However, as a representative MDM, I believe SEDD can also break the reversal curse.

**Comment by richardzhuang0412** [comment]
Thanks for the clarification! As a follow-up, could you briefly explain the difference between MDM and SEDD? I thought SEDD is the only implementation that allows diffusion model to be used for text generation. Could you guide me to any materials of MDM's foundation?

**Comment by nieshenx** [comment]
I recommend reading Section 2 of our paper. To the best of my knowledge, it offers the simplest introduction to masked diffusion models for text.

Regarding SEDD, it introduces a novel formulation for discrete diffusion models, distinguishing between two types: masked diffusion models and uniform diffusion models. Since masked diffusion models significantly outperform uniform diffusion models, we focus on the masked diffusion models.

Even though both SEDD and our models are masked diffusion models, we follow [RADD](https://arxiv.org/abs/2406.03736) and adopt a loss function that differs slightly from SEDD’s. The difference is as follows: 
![sedd](https://github.com/user-attachments/assets/1a2ee33a-aeb5-49c1-813a-dfd2adcd907e)

You can read SEDD, [RADD](https://arxiv.org/abs/2406.03736), [MDLM](https://arxiv.org/abs/2406.07524) and our paper for more details about masked diffusion models.

**Comment by richardzhuang0412** [comment]
Appreciate the thorough response!
